=begin
#cryptkeeper-jets-sandbox

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2022-02-28T21:29:17Z

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

require 'spec_helper'
require 'json'

# Unit tests for CryptkeeperApiClient::DefaultApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @instance = CryptkeeperApiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@instance).to be_instance_of(CryptkeeperApiClient::DefaultApi)
    end
  end

  # unit tests for api_v1_participants_id_accounts_currency_get
  # @param id 
  # @param currency 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_participants_id_accounts_currency_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for api_v1_trades_post
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'api_v1_trades_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for root_get
  # @param [Hash] opts the optional parameters
  # @return [Empty]
  describe 'root_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
