=begin
#cryptkeeper-jets-sandbox

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2022-02-28T21:29:17Z

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CryptkeeperApiClient::Empty
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Empty' do
  before do
    # run before each test
    @instance = CryptkeeperApiClient::Empty.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Empty' do
    it 'should create an instance of Empty' do
      expect(@instance).to be_instance_of(CryptkeeperApiClient::Empty)
    end
  end
end
