=begin
#cryptkeeper-jets-sandbox

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2022-03-06T22:32:28Z

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

# Common files
require 'cryptkeeper-api-client/api_client'
require 'cryptkeeper-api-client/api_error'
require 'cryptkeeper-api-client/version'
require 'cryptkeeper-api-client/configuration'

# Models

# APIs
require 'cryptkeeper-api-client/api/default_api'

module CryptkeeperApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CryptkeeperApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
