=begin
#cryptkeeper-jets-sandbox

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 2022-03-06T22:32:28Z

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

module CryptkeeperApiClient
  VERSION = '0.0.1'
end
