=begin
#cryptkeeper-jets-sandbox

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2022-03-06T22:32:28Z

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.33
=end

module CryptkeeperApiClient
  VERSION = '0.0.1'
end
